# -*- coding: utf-8 -*-
"""
Ecological Evaluation Module for Urban Trees
城市树木生态学评估模块 (碳汇计算)
"""
import numpy as np
from typing import Dict, Any
from .config import get_species_params

# =========================================================================
# Module 1: Carbon Sink Calculation / 模块一：碳汇计算
# =========================================================================
def calculate_implicit_carbon(physics_result: Dict[str, Any], species_name: str, hours: float = 4380) -> Dict[str, float]:
    """
    Calculate the implicit carbon sink generated by artificial night lighting.
    计算由人工夜间照明产生的隐性碳汇 (Implicit Carbon Sink)。
    
    Logic aligns with v4.5 script / 逻辑与 v4.5 脚本一致:
    1. Only count regions where PPFD > 0.01 (effective light-receiving area) / 仅统计 PPFD > 0.01 的有效受光面
    2. Gain formula / 增量公式: Gain = alpha * PPFD * Area * Time
    3. Dark respiration (Rd) is not subtracted, as this calculates the "additional" benefit from artificial light 
       / 不减去 Rd (呼吸消耗)，因为这里计算的是人工光带来的“额外”光合收益。

    Args:
        physics_result (Dict[str, Any]): Result dictionary from physical lighting simulation / 物理光照模拟的返回结果
        species_name (str): The specific tree species name / 目标树种名称
        hours (float): Total lighting hours in a year (default: 12 hours/day * 365 days = 4380) 
                       / 全年照明总小时数 (默认: 12小时/天 * 365天 = 4380小时)

    Returns:
        Dict[str, float]: Dictionary containing carbon reduction amount and valid area ratio / 包含碳减排量与有效受光面积比率的字典
    """
    # Extract PPFD and areas from physics results / 提取物理结果中的 PPFD 和面积数据
    ppfd = physics_result["ppfd_raw"]
    areas = physics_result["areas"]
    
    # Retrieve physiological parameters for the species / 获取对应树种的生理参数
    params = get_species_params(species_name)
    alpha = params["alpha"] # AQY (Apparent Quantum Yield) / 表观量子效率
    
    # Filter valid regions (PPFD > 0.01) / 筛选有效受光区域 (> 0.01)
    mask = ppfd > 0.01
    
    # If no valid area is illuminated, return zero / 如果没有有效受光面，直接返回 0
    if not np.any(mask):
        return {
            "species": species_name,
            "carbon_g": 0.0,
            "valid_area_ratio": 0.0
        }
    
    # Step 1: Calculate Total Photosynthetic Flux (μmol/s) / 第一步：计算总光合通量 (微摩尔/秒)
    # Formula: Flux = Sum( alpha * PPFD_i * Area_i )
    flux_total = np.sum(ppfd[mask] * areas[mask]) * alpha
    
    # Step 2: Integrate over time to calculate total carbon mass (g) / 第二步：时间积分计算总碳质量 (克)
    # Unit conversions / 单位换算逻辑:
    # 1e-6: μmol -> mol (微摩尔转摩尔)
    # 44:   mol -> g of CO2 (摩尔转二氧化碳克数)
    # 3600 * hours: Total seconds (总秒数)
    total_carbon_g = flux_total * 1e-6 * 44 * (hours * 3600)
    
    return {
        "species": species_name,
        "carbon_g": total_carbon_g,
        "valid_area_ratio": np.sum(areas[mask]) / np.sum(areas)
    }
